typicalninja/google-sr

- .github/workflows/pr-lint.yml
- .github/workflows/tests.yml
- package.json
Current workflows contains outdated action versions.
Refer below:
pnpm/action-setup@v2 -> pnpm/action-setup@v4 (https://github.com/pnpm/action-setup/issues/135)
actions/setup-node@v3 -> actions/setup-node@v4 (now using node 20x)
Some names of the workflows were renamed to better reflect on what they do.
> chore: Update workflows

- README.md
- packages/google-sr-selectors/README.md
- packages/google-sr/README.md
- packages/google-that/README.md
We are removing the vercel/vitepress docs in favor of github pages and readme docs
> chore: move docs to readme

- packages/google-sr/src/index.ts
- packages/google-sr/src/search.ts
- packages/google-sr/src/utils.ts
The utility types `ResultNodeTyper` and `SearchResultTypeFromSelector` (renamed) were not exported. While they are internal types, they are required for advanced use cases.
> chore: fix some required exports missing

- packages/google-sr/tests/paged.test.ts
- packages/google-sr/tests/result.test.ts
Previously we were only checking if a returned value is a string. how ever some selectors may return a empty string in the current implementation, for now we will include a check to see if a value is empty. (in the future we may instead make all empty strings return null)
NOTE: currently the test fails since 2 selectors are returning an empty string. another pr will fix it.
> test: ensure tests check each property to not be a empty string

- .changeset/tidy-ducks-end.md
- packages/google-sr-selectors/src/index.ts
- packages/google-sr/tests/result.test.ts
New selector: `div:not([data-hveid]):not(.yStFkb) > div.Gx5Zad.xpd.EtOod.pkphOe`
`data-hveid` and `.yStFkb` filters our similar questions section.
> refactor(selectors): Patch organic search result

- packages/google-sr/tests/result.test.ts
Just a simple fix. old query did not return a result with `translationPronunciation` so tests were failing.
> test(gsr): Fix translate query test

- .changeset/cyan-hotels-yawn.md
- .changeset/selfish-trains-exist.md
- apps/examples/src/custom-selector.ts
- packages/google-sr/src/constants.ts
Simple type change to allow custom selectors. custom selectors were implemented in #15
> refactor: add support for custom selectors

- packages/google-sr/tests/paged.test.ts
- packages/google-sr/tests/result.test.ts
on some platforms (i.e github actions) it returns some weird results that does not have a link/description/title.
The result look something like this:
```js
{
title: "Visual studio codeVisual Studio" // exact text
description: null
link: null
}
```
until we can figure this out and since it works on local machine i am putting a band aid fix by setting strict selector to true
> test: temp band aid fix for tests failing on actions

- .changeset/pretty-forks-shout.md
- README.md
- apps/examples/package.json
- apps/examples/src/proxies.ts
- packages/google-sr/src/constants.ts
- packages/google-sr/src/utils.ts
Removes the `safemode` top-level options as the same result can be achieved using the `requestConfig` option.
Also adds a proxy example to showcase using `requestConfig`.
> chore: remove uneeded toplevel options

- README.md
- packages/google-sr-selectors/README.md
- packages/google-sr/README.md
- packages/google-that/README.md
I have verified the package works on deno with the `npm:` specifier. this adds the note mentioning this. 
The disclaimer was moved bit up for visibility.
> docs: mention deno install/support in readme

- .changeset/fluffy-numbers-provide.md
- .changeset/giant-books-peel.md
- .changeset/violet-actors-care.md
- packages/google-sr-selectors/src/index.ts
- packages/google-sr/src/constants.ts
- packages/google-sr/src/results.ts
- packages/google-sr/src/utils.ts
- packages/google-sr/tests/result.test.ts
- packages/google-that/src/helpers.ts
This pr implements support for knowledge graph results.
Query example: ["Interstellar"](https://www.google.com/search?hl=en&q=Interstellar) should return information about the movie in a separate panel.
> feat: Add knowledge graph results

- .changeset/smart-clouds-own.md
- packages/google-sr-selectors/src/index.ts
There were some recent changes to how google sends the result for translations. the selects for target & source langs now contain dynamic ids. instead we are now relying on a static id property.
> refactor: patch translation selectors

- .changeset/chilly-yaks-kick.md
- .changeset/cold-masks-bathe.md
- .changeset/olive-panthers-sin.md
- .changeset/selfish-comics-give.md
- .changeset/serious-walls-turn.md
- .changeset/sour-bears-visit.md
- apps/examples/src/translate.ts
- apps/scraper/search-dump.js
- packages/google-sr-selectors/README.md
- packages/google-sr-selectors/package.json
- packages/google-sr-selectors/src/index.ts
- packages/google-sr/README.md
- packages/google-sr/package.json
- packages/google-sr/src/constants.ts
- packages/google-sr/src/results.ts
- packages/google-sr/src/utils.ts
- packages/google-sr/tests/result.test.ts
- packages/google-that/README.md
In a recent Google update, the ability to access search result pages without enabling JavaScript was disabled. (See [#51](https://github.com/typicalninja/google-sr/issues/51) for more details.)
Using resources such as [this Hacker News thread](https://news.ycombinator.com/item?id=42743344), I implemented a workaround that bypasses the JavaScript requirement by utilizing an alternate page version served to specific user agents.
However, this alternate page lacks certain features available on the standard page, resulting in the removal of some properties. Please refer to the changelog for a detailed list of changes.
**Closes #51**
> refactor: bypass JavaScript requirement for Google search

- packages/google-sr/package.json
- pnpm-lock.yaml
PR #65 updated all dependencies to their latest versions. However, cheerio introduced a breaking change without a corresponding major version bump, which is currently causing GitHub Actions to fail.
This PR is a temporary fix to restore functionality until the issue is resolved.
> chore: revert cheerio to v1.0.0-rc.12 to fix type issues

- .changeset/legal-trams-sit.md
- packages/google-sr/src/results/news.ts
- packages/google-sr/src/utils.ts
- packages/google-sr/tests/results.test.ts
- packages/google-sr/tests/search.test.ts
- packages/google-sr/tests/utils.test.ts
This fixes 3 tests and modifies utility function `safeGetFetch` and `prepareRequestConfig` to not modify the passed in options object directly. 
Additionally the changeset for NewsSearchSelector (added in #71) was updated to contain a description and an example
> test(google-sr): fix tests and update documentation

- .changeset/fast-moose-lay.md
- apps/examples/src/kitchen-sink.ts
- packages/google-sr-selectors/src/index.ts
- packages/google-sr/src/constants.ts
- packages/google-sr/src/results/conversion.ts
- packages/google-sr/src/results/index.ts
- packages/google-sr/tests/results.test.ts
- packages/google-that/src/constants.ts
- packages/google-that/src/helpers.ts
The original `CurrencyResult` selector was found to work effectively for all types of conversion queries (currency, distance, weight, temperature, etc.), not just currency conversions. The rename better captures its actual functionality and makes the API more intuitive for users performing various conversion searches.
> refactor: rename CurrencyResult to UnitConversionResult

- .changeset/cuddly-bars-do.md
- packages/google-sr/src/results/conversion.ts
- packages/google-sr/src/results/dictionary.ts
- packages/google-sr/src/results/knowledge-panel.ts
- packages/google-sr/src/results/news.ts
- packages/google-sr/src/results/organic.ts
- packages/google-sr/src/results/time.ts
- packages/google-sr/src/results/translate.ts
- packages/google-sr/src/utils.ts
Currently, the parser processes all values before checking if they are empty at the end of the parsing cycle. This approach wastes computational resources when `noPartialResults` is enabled, as the parser continues processing even when it encounters empty data that will ultimately be rejected.
This change moves the validation check to occur immediately after parsing the DOM node. If the data is empty and `noPartialResults` is enabled, the parser now returns null early in the process.
> refactor: skip parsing when data is empty and partial results are disabled

- packages/google-sr/src/utils.ts
A bug was introduced in #75 where `prepareRequestConfig` would attempt to validate `requestConfig` options even when the parameter was not provided, causing validation to fail on undefined values.
This broke the following usage pattern:
```ts
search({
query: "Some query"
// requestConfig omitted - should be valid but was throwing validation error
})
```
Added an existence check for `requestConfig` before running validation to ensure it only validates when the parameter is explicitly provided.
> fix: validation error when requestConfig is undefined / null

- README.md
- packages/google-sr-selectors/README.md
- packages/google-sr/README.md
This PR adds a section to the README to inform users that support for the CommonJS (CJS) build will be removed in a future major release (v7.x, subject to change). The package will transition to ES Modules (ESM)-only once Node.js v20 reaches End-of-Life (EOL).
Motivation
- Modern JavaScript ecosystems have standardized around ESM.
- Node.js v20+ [supports require() on ESM modules natively](https://nodejs.org/en/blog/release/v20.19.0/).
- Maintaining both CJS and ESM builds increases package size and build complexity.
- Popular runtimes like Bun and Deno already support ESM-only packages.
> If a breaking change requires a major version bump before that point, the CJS deprecation will be deferred to the following major version.
If you have any feedback regarding this, please see the …
> docs: add cjs deprecation notice to readme

- packages/google-sr/package.json
- packages/google-sr/src/results/dictionary.ts
- pnpm-lock.yaml
Version [1.x of cheerio had several breaking changes](https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0) from the previous RC (release candidate) version, blocking us from updating.
This adapts the changes necessary and updates the cheerio dependency to [v1.1.0](https://github.com/cheeriojs/cheerio/releases/tag/v1.1.0)
> chore: update cheerio to v1.1.0

- packages/google-sr/src/results/news.ts
- packages/google-sr/tests/results.test.ts
Some news results do not contain thumbnail images.
> refactor: make thumbnail_image in news results optional

- .changeset/tame-schools-kick.md
- packages/google-sr/src/results/organic.ts
- packages/google-sr/tests/results.test.ts
Makes the `description` field in `OrganicResultNode` optional to handle cases where search results don't include a description.
- Changed `description: string` to `description?: string | undefined` in `OrganicResultNode`
> feat(google-sr): make OrganicResult description field optional

- apps/scraper/search-dump.ts
- packages/google-sr-selectors/README.md
- packages/google-sr/src/constants.ts
- packages/google-sr/src/search.ts
- packages/google-sr/src/utils.ts
- packages/google-sr/tests/utils.test.ts
In #75, when we replaced `axios` with native fetch we were getting `ISO-8859-1` encoded text for the user-agent we used. with further experimentation I was able to make google send `UTF-8` encoded text via an `IE 9` user-agent. additionally, the user-agent mentioned in the `google-sr-selectors` README was updated to the new one we use to prevent confusion.
> refactor(google-sr): use utf-8 to decode http response

- packages/google-sr/src/constants.ts
- packages/google-sr/src/index.ts
- packages/google-sr/src/results/conversion.ts
- packages/google-sr/src/results/dictionary.ts
- packages/google-sr/src/results/knowledge-panel.ts
- packages/google-sr/src/results/news.ts
- packages/google-sr/src/results/organic.ts
- packages/google-sr/src/results/related-searches.ts
- packages/google-sr/src/results/time.ts
- packages/google-sr/src/results/translate.ts
- packages/google-sr/src/search.ts
- packages/google-sr/src/utils.ts
This PR standardizes the TSDoc documentation across all result parsers and core internal interfaces to improve developer and contributor experience.
- **Result Parsers**: Unified JSDoc format with consistent parameter documentation, practical examples, and proper type linking across all 8 result parsers
- **Core Interfaces**: Enhanced documentation for `SearchOptions` and `SearchOptionsWithPages` with detailed examples and better explanations of configuration options
- **Utility Functions**: Improved internal function documentation and standardized visibility tags
All changes are documentation-only with no functional modifications to the codebase.
> docs: standardize TSDoc comments across result parsers and core interfaces
